# Generated by Django 2.2.2 on 2019-07-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accelerator',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='logos'),
        ),
    ]
